<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProfileBuilderFieldsSeeder extends Seeder
{
    public function run(): void
    {
        $fields = [
            // ==================== PROFILE TAB ====================
            [
                'tab' => 'profile',
                'field_key' => 'image',
                'field_type' => 'image',
                'label' => 'Profile Picture',
                'placeholder' => null,
                'help_text' => 'JPG, PNG, GIF or WebP. Max 5MB',
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 5120]),
                'available_plans' => json_encode(['basic', 'premium', 'business']),
                'display_order' => 10,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'profile',
                'field_key' => 'name',
                'field_type' => 'text',
                'label' => 'Name',
                'placeholder' => 'Your name',
                'help_text' => null,
                'is_required' => true,
                'is_visible' => true,
                'validation_rules' => json_encode(['min' => 2, 'max' => 100]),
                'available_plans' => json_encode(['basic', 'premium', 'business']),
                'display_order' => 20,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'profile',
                'field_key' => 'position',
                'field_type' => 'text',
                'label' => 'Position',
                'placeholder' => 'Your job title',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 100]),
                'available_plans' => json_encode(['basic', 'premium', 'business']),
                'display_order' => 30,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'profile',
                'field_key' => 'qualification',
                'field_type' => 'text',
                'label' => 'Qualification',
                'placeholder' => 'e.g., Bachelor of Business Administration',
                'help_text' => 'Optional',
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 200]),
                'available_plans' => json_encode(['premium', 'business']),
                'display_order' => 35,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'profile',
                'field_key' => 'bio',
                'field_type' => 'textarea',
                'label' => 'Bio',
                'placeholder' => 'Tell visitors about yourself...',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 500]),
                'available_plans' => json_encode(['basic', 'premium', 'business']),
                'display_order' => 40,
                'config' => json_encode(['rows' => 4]),
            ],
            [
                'tab' => 'profile',
                'field_key' => 'contactNumber',
                'field_type' => 'tel',
                'label' => 'Contact Number',
                'placeholder' => '+60 12-345 6789',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 20]),
                'available_plans' => json_encode(['basic', 'premium', 'business']),
                'display_order' => 50,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'profile',
                'field_key' => 'email',
                'field_type' => 'email',
                'label' => 'Email Address',
                'placeholder' => 'your@email.com',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 255]),
                'available_plans' => json_encode(['basic', 'premium', 'business']),
                'display_order' => 60,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'profile',
                'field_key' => 'website',
                'field_type' => 'url',
                'label' => 'Website',
                'placeholder' => 'https://yourwebsite.com',
                'help_text' => 'Optional',
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 255]),
                'available_plans' => json_encode(['basic', 'premium', 'business']),
                'display_order' => 70,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'profile',
                'field_key' => 'address',
                'field_type' => 'textarea',
                'label' => 'Address',
                'placeholder' => 'Your business address',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 300]),
                'available_plans' => json_encode(['basic', 'premium', 'business']),
                'display_order' => 80,
                'config' => json_encode(['rows' => 2]),
            ],
            [
                'tab' => 'profile',
                'field_key' => 'stats',
                'field_type' => 'repeater',
                'label' => 'Profile Statistics',
                'placeholder' => null,
                'help_text' => 'Add up to 3 statistics to showcase your achievements',
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode([]),
                'available_plans' => json_encode(['premium', 'business']),
                'display_order' => 90,
                'config' => json_encode([
                    'max_items' => 3,
                    'sub_fields' => [
                        ['key' => 'num', 'label' => 'Number', 'type' => 'text', 'placeholder' => 'e.g., 10+'],
                        ['key' => 'label', 'label' => 'Label', 'type' => 'text', 'placeholder' => 'e.g., Years Experience']
                    ]
                ]),
            ],

            // ==================== COMPANY TAB ====================
            [
                'tab' => 'company',
                'field_key' => 'companyLogo',
                'field_type' => 'image',
                'label' => 'Company Logo',
                'placeholder' => null,
                'help_text' => 'Will appear as background watermark',
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 5120]),
                'available_plans' => json_encode(['business']),
                'display_order' => 100,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'companyLogoText',
                'field_type' => 'text',
                'label' => 'Company Logo Text',
                'placeholder' => 'e.g., COMPANY',
                'help_text' => 'Text overlay for company logo',
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 50]),
                'available_plans' => json_encode(['business']),
                'display_order' => 110,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'companyName',
                'field_type' => 'text',
                'label' => 'Company Name',
                'placeholder' => 'e.g., ABC Corporation Sdn. Bhd.',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 200]),
                'available_plans' => json_encode(['business']),
                'display_order' => 120,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'companyRegistrationNo',
                'field_type' => 'text',
                'label' => 'Company Registration No.',
                'placeholder' => 'e.g., 202201234567 (1234567-A)',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 100]),
                'available_plans' => json_encode(['business']),
                'display_order' => 130,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'companyDepartment',
                'field_type' => 'text',
                'label' => 'Department',
                'placeholder' => 'e.g., Sales & Marketing',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 100]),
                'available_plans' => json_encode(['business']),
                'display_order' => 140,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'addressName',
                'field_type' => 'text',
                'label' => 'Location Name',
                'placeholder' => 'e.g., Headquarters',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 100]),
                'available_plans' => json_encode(['business']),
                'display_order' => 150,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'addressStreet',
                'field_type' => 'text',
                'label' => 'Street Address',
                'placeholder' => 'e.g., 123 Business Street',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 200]),
                'available_plans' => json_encode(['business']),
                'display_order' => 160,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'addressArea',
                'field_type' => 'text',
                'label' => 'Area',
                'placeholder' => 'e.g., Taman ABC',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 100]),
                'available_plans' => json_encode(['business']),
                'display_order' => 170,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'addressCityState',
                'field_type' => 'text',
                'label' => 'City, State',
                'placeholder' => 'e.g., 50000 Kuala Lumpur',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 100]),
                'available_plans' => json_encode(['business']),
                'display_order' => 180,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'addressCountry',
                'field_type' => 'text',
                'label' => 'Country',
                'placeholder' => 'e.g., Malaysia',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 100]),
                'available_plans' => json_encode(['business']),
                'display_order' => 190,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'addressMapUrl',
                'field_type' => 'url',
                'label' => 'Map URL',
                'placeholder' => 'e.g., https://maps.google.com/...',
                'help_text' => 'Google Maps or other map service link',
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 500]),
                'available_plans' => json_encode(['business']),
                'display_order' => 200,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'phoneLabel',
                'field_type' => 'text',
                'label' => 'Phone Label',
                'placeholder' => 'e.g., Call Us',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 50]),
                'available_plans' => json_encode(['business']),
                'display_order' => 210,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'phoneNumber',
                'field_type' => 'tel',
                'label' => 'Phone Number',
                'placeholder' => 'e.g., +60123456789',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 20]),
                'available_plans' => json_encode(['business']),
                'display_order' => 220,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'emailLabel',
                'field_type' => 'text',
                'label' => 'Email Label',
                'placeholder' => 'e.g., Email Us',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 50]),
                'available_plans' => json_encode(['business']),
                'display_order' => 230,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'emailAddress',
                'field_type' => 'email',
                'label' => 'Email Address',
                'placeholder' => 'e.g., info@company.com',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 255]),
                'available_plans' => json_encode(['business']),
                'display_order' => 240,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'whatsappLabel',
                'field_type' => 'text',
                'label' => 'WhatsApp Label',
                'placeholder' => 'e.g., WhatsApp',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 50]),
                'available_plans' => json_encode(['business']),
                'display_order' => 250,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'whatsappNumber',
                'field_type' => 'tel',
                'label' => 'WhatsApp Number',
                'placeholder' => 'e.g., +60123456789',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 20]),
                'available_plans' => json_encode(['business']),
                'display_order' => 260,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'websiteLabel',
                'field_type' => 'text',
                'label' => 'Website Label',
                'placeholder' => 'e.g., Visit Website',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 50]),
                'available_plans' => json_encode(['business']),
                'display_order' => 270,
                'config' => json_encode([]),
            ],
            [
                'tab' => 'company',
                'field_key' => 'websiteUrl',
                'field_type' => 'url',
                'label' => 'Website URL',
                'placeholder' => 'e.g., https://company.com',
                'help_text' => null,
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode(['max' => 255]),
                'available_plans' => json_encode(['business']),
                'display_order' => 280,
                'config' => json_encode([]),
            ],

            // ==================== SERVICES TAB ====================
            [
                'tab' => 'services',
                'field_key' => 'services',
                'field_type' => 'repeater',
                'label' => 'Our Services',
                'placeholder' => null,
                'help_text' => 'Add up to 6 services your company offers',
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode([]),
                'available_plans' => json_encode(['premium', 'business']),
                'display_order' => 300,
                'config' => json_encode([
                    'max_items' => 6,
                    'sub_fields' => [
                        ['key' => 'icon', 'label' => 'Icon', 'type' => 'text', 'placeholder' => 'e.g., 🏢'],
                        ['key' => 'name', 'label' => 'Service Name', 'type' => 'text', 'placeholder' => 'e.g., Consulting']
                    ]
                ]),
            ],
            [
                'tab' => 'services',
                'field_key' => 'teamMembers',
                'field_type' => 'repeater',
                'label' => 'Team Members',
                'placeholder' => null,
                'help_text' => 'Add up to 3 key team members to display',
                'is_required' => false,
                'is_visible' => true,
                'validation_rules' => json_encode([]),
                'available_plans' => json_encode(['business']),
                'display_order' => 310,
                'config' => json_encode([
                    'max_items' => 3,
                    'sub_fields' => [
                        ['key' => 'initials', 'label' => 'Initials', 'type' => 'text', 'placeholder' => 'e.g., JD', 'maxlength' => 2],
                        ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'placeholder' => 'e.g., John Doe'],
                        ['key' => 'role', 'label' => 'Role', 'type' => 'text', 'placeholder' => 'e.g., CEO']
                    ]
                ]),
            ],
        ];

        foreach ($fields as $field) {
            DB::table('profile_builder_fields')->updateOrInsert(
                ['field_key' => $field['field_key']],
                $field
            );
        }

        $this->command->info('Profile builder fields seeded successfully!');
    }
}
