<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProfileDesignOptionSeeder extends Seeder
{
    public function run(): void
    {
        $options = [
            // ========== THEMES (12 premium presets) ==========
            [
                'type' => 'theme',
                'option_id' => 'minimal',
                'name' => 'Minimal',
                'description' => 'Clean white background with subtle contrast — perfect for professional use.',
                'config' => [
                    'backgroundColor' => '#FFFFFF',
                    'textColor' => '#111827',
                    'accentColor' => '#1F2937',
                    'previewCss' => 'background: #FFFFFF;',
                    'bgGradient' => null,
                ],
                'is_active' => true,
                'is_default' => true,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 1,
            ],
            [
                'type' => 'theme',
                'option_id' => 'modern',
                'name' => 'Modern Soft',
                'description' => 'Light gray gradient with soft shadows — contemporary and easy on the eyes.',
                'config' => [
                    'backgroundColor' => '#F9FAFB',
                    'textColor' => '#111827',
                    'accentColor' => '#2563EB',
                    'previewCss' => 'background: linear-gradient(135deg, #F9FAFB 0%, #E5E7EB 100%);',
                    'bgGradient' => 'linear-gradient(135deg, #F9FAFB 0%, #E5E7EB 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 2,
            ],
            [
                'type' => 'theme',
                'option_id' => 'creative',
                'name' => 'Creative',
                'description' => 'Vibrant pink-to-purple gradient — for creative agencies and personal brands.',
                'config' => [
                    'backgroundColor' => '#A855F7',
                    'textColor' => '#FFFFFF',
                    'accentColor' => '#EC4899',
                    'previewCss' => 'background: linear-gradient(135deg, #A855F7 0%, #EC4899 100%);',
                    'bgGradient' => 'linear-gradient(135deg, #A855F7 0%, #EC4899 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 3,
            ],
            [
                'type' => 'theme',
                'option_id' => 'zora-pro',
                'name' => 'Zora Pro',
                'description' => 'Premium Navy + Matte Teal theme with high readability and elegant contrast.',
                'config' => [
                    'backgroundColor' => '#0F2744',
                    'textColor' => '#E8EEF4',
                    'accentColor' => '#5B8A86',
                    'previewCss' => 'background: linear-gradient(160deg, #0F2744 0%, #18395E 55%, #1F5177 100%);',
                    'bgGradient' => 'linear-gradient(160deg, #0F2744 0%, #18395E 55%, #1F5177 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 4,
            ],
            [
                'type' => 'theme',
                'option_id' => 'professional',
                'name' => 'Corporate Blue',
                'description' => 'Strong blue gradient — ideal for companies and institutions.',
                'config' => [
                    'backgroundColor' => '#2563EB',
                    'textColor' => '#FFFFFF',
                    'accentColor' => '#1E40AF',
                    'previewCss' => 'background: linear-gradient(135deg, #2563EB 0%, #1E40AF 100%);',
                    'bgGradient' => 'linear-gradient(135deg, #2563EB 0%, #1E40AF 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 5,
            ],
            [
                'type' => 'theme',
                'option_id' => 'dark',
                'name' => 'Dark',
                'description' => 'Deep near-black matte theme — for sleek modern tech profiles.',
                'config' => [
                    'backgroundColor' => '#111827',
                    'textColor' => '#F9FAFB',
                    'accentColor' => '#60A5FA',
                    'previewCss' => 'background: linear-gradient(135deg, #111827 0%, #0B1220 100%);',
                    'bgGradient' => 'linear-gradient(135deg, #111827 0%, #0B1220 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 6,
            ],
            [
                'type' => 'theme',
                'option_id' => 'warm-sand',
                'name' => 'Warm Sand',
                'description' => 'Soft cream and earth tones — warm, inviting, and mature aesthetic.',
                'config' => [
                    'backgroundColor' => '#FBF7F0',
                    'textColor' => '#3F3427',
                    'accentColor' => '#B45309',
                    'previewCss' => 'background: linear-gradient(135deg, #FBF7F0 0%, #F3EADB 50%, #E9D9BE 100%);',
                    'bgGradient' => 'linear-gradient(135deg, #FBF7F0 0%, #F3EADB 50%, #E9D9BE 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 7,
            ],
            [
                'type' => 'theme',
                'option_id' => 'deep-charcoal',
                'name' => 'Deep Charcoal',
                'description' => 'Matte dark gray (not OLED black) — gentle contrast for low-light use.',
                'config' => [
                    'backgroundColor' => '#1E293B',
                    'textColor' => '#E2E8F0',
                    'accentColor' => '#60A5FA',
                    'previewCss' => 'background: linear-gradient(160deg, #1E293B 0%, #0F172A 100%);',
                    'bgGradient' => 'linear-gradient(160deg, #1E293B 0%, #0F172A 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 8,
            ],
            [
                'type' => 'theme',
                'option_id' => 'sunset-gold',
                'name' => 'Sunset Gold',
                'description' => 'Warm orange-to-rose sunset — energetic, for lifestyle and food brands.',
                'config' => [
                    'backgroundColor' => '#F97316',
                    'textColor' => '#FFFBEB',
                    'accentColor' => '#F59E0B',
                    'previewCss' => 'background: linear-gradient(135deg, #F97316 0%, #EF4444 45%, #DB2777 100%);',
                    'bgGradient' => 'linear-gradient(135deg, #F97316 0%, #EF4444 45%, #DB2777 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 9,
            ],
            [
                'type' => 'theme',
                'option_id' => 'ocean-breeze',
                'name' => 'Ocean Breeze',
                'description' => 'Cyan-to-teal ocean gradient — for resort, tourism, and wellness.',
                'config' => [
                    'backgroundColor' => '#0EA5E9',
                    'textColor' => '#ECFEFF',
                    'accentColor' => '#14B8A6',
                    'previewCss' => 'background: linear-gradient(160deg, #0284C7 0%, #0EA5E9 40%, #14B8A6 100%);',
                    'bgGradient' => 'linear-gradient(160deg, #0284C7 0%, #0EA5E9 40%, #14B8A6 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 10,
            ],
            [
                'type' => 'theme',
                'option_id' => 'emerald-forest',
                'name' => 'Emerald Forest',
                'description' => 'Rich green and emerald palette — for eco, nature, and property brands.',
                'config' => [
                    'backgroundColor' => '#166534',
                    'textColor' => '#F0FDF4',
                    'accentColor' => '#84CC16',
                    'previewCss' => 'background: linear-gradient(160deg, #065F46 0%, #047857 40%, #166534 100%);',
                    'bgGradient' => 'linear-gradient(160deg, #065F46 0%, #047857 40%, #166534 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 11,
            ],
            [
                'type' => 'theme',
                'option_id' => 'sakura-dusk',
                'name' => 'Sakura Dusk',
                'description' => 'Soft blush and lavender tones — feminine, premium, elegant.',
                'config' => [
                    'backgroundColor' => '#FCE7F3',
                    'textColor' => '#831843',
                    'accentColor' => '#A78BFA',
                    'previewCss' => 'background: linear-gradient(135deg, #FCE7F3 0%, #EDE9FE 50%, #DBEAFE 100%);',
                    'bgGradient' => 'linear-gradient(135deg, #FCE7F3 0%, #EDE9FE 50%, #DBEAFE 100%)',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 12,
            ],

            // ========== FONTS ==========
            [
                'type' => 'font',
                'option_id' => 'inter',
                'name' => 'Inter',
                'description' => 'Modern sans-serif — clean, legible, default choice.',
                'config' => [
                    'family' => 'Inter, system-ui, -apple-system, sans-serif',
                    'weights' => [400, 500, 600, 700],
                ],
                'is_active' => true,
                'is_default' => true,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 1,
            ],
            [
                'type' => 'font',
                'option_id' => 'poppins',
                'name' => 'Poppins',
                'description' => 'Geometric sans-serif — friendly and contemporary.',
                'config' => [
                    'family' => 'Poppins, Inter, system-ui, sans-serif',
                    'weights' => [400, 500, 600, 700],
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 2,
            ],
            [
                'type' => 'font',
                'option_id' => 'roboto',
                'name' => 'Roboto',
                'description' => 'Classic Android font — neutral and universally readable.',
                'config' => [
                    'family' => 'Roboto, Inter, system-ui, sans-serif',
                    'weights' => [400, 500, 700],
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 3,
            ],
            [
                'type' => 'font',
                'option_id' => 'plus-jakarta',
                'name' => 'Plus Jakarta',
                'description' => 'Premium geometric sans — luxurious modern editorial feel.',
                'config' => [
                    'family' => '"Plus Jakarta Sans", Poppins, sans-serif',
                    'weights' => [400, 500, 600, 700, 800],
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 4,
            ],
            [
                'type' => 'font',
                'option_id' => 'playfair',
                'name' => 'Playfair Display',
                'description' => 'Elegant serif — perfect for luxury, legal, or editorial brands.',
                'config' => [
                    'family' => 'Playfair Display, Georgia, serif',
                    'weights' => [400, 500, 600, 700],
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 5,
            ],
            [
                'type' => 'font',
                'option_id' => 'lora',
                'name' => 'Lora',
                'description' => 'Highly readable serif — comfortable for long-form text.',
                'config' => [
                    'family' => 'Lora, Georgia, serif',
                    'weights' => [400, 500, 600, 700],
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 6,
            ],
            [
                'type' => 'font',
                'option_id' => 'space-grotesk',
                'name' => 'Space Grotesk',
                'description' => 'Contemporary tech sans — for startups, fintech, and developer brands.',
                'config' => [
                    'family' => '"Space Grotesk", Inter, sans-serif',
                    'weights' => [400, 500, 600, 700],
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 7,
            ],

            // ========== BUTTON STYLES ==========
            [
                'type' => 'button_style',
                'option_id' => 'solid',
                'name' => 'Solid Pill',
                'description' => 'Full-color rounded pill button — high visibility.',
                'config' => [
                    'class' => 'bg-foreground text-background font-semibold rounded-full',
                ],
                'is_active' => true,
                'is_default' => true,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 1,
            ],
            [
                'type' => 'button_style',
                'option_id' => 'outline',
                'name' => 'Outline Pill',
                'description' => 'Bordered button with transparent background — understated.',
                'config' => [
                    'class' => 'border-2 border-foreground text-foreground font-medium rounded-full',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 2,
            ],
            [
                'type' => 'button_style',
                'option_id' => 'soft',
                'name' => 'Soft Rounded',
                'description' => 'Muted surface tone with rounded corners — modern and gentle.',
                'config' => [
                    'class' => 'bg-white/15 backdrop-blur-md text-foreground font-medium rounded-2xl border border-white/20',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 3,
            ],
            [
                'type' => 'button_style',
                'option_id' => 'shadow',
                'name' => 'Elevation Shadow',
                'description' => 'White surface with soft drop shadow — elevated card style.',
                'config' => [
                    'class' => 'bg-white text-gray-900 font-semibold rounded-2xl shadow-lg hover:shadow-xl',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 4,
            ],
            [
                'type' => 'button_style',
                'option_id' => 'gradient',
                'name' => 'Gradient Glow',
                'description' => 'Animated gradient pill with subtle glow — premium attention.',
                'config' => [
                    'class' => 'bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white font-semibold rounded-full shadow-lg shadow-purple-500/25',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 5,
            ],
            [
                'type' => 'button_style',
                'option_id' => 'square',
                'name' => 'Sharp Square',
                'description' => 'No-radius sharp corners — minimalist brutalist style.',
                'config' => [
                    'class' => 'bg-foreground text-background font-semibold rounded-none',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 6,
            ],

            // ========== CARD STYLES (section container styling) ==========
            [
                'type' => 'card_style',
                'option_id' => 'minimal',
                'name' => 'Minimal Clean',
                'description' => 'Soft solid surface with subtle border — pure, uncluttered.',
                'config' => [
                    'class' => 'bg-white/90 backdrop-blur-sm rounded-2xl border border-gray-200/60',
                    'previewCss' => 'background: rgba(255,255,255,0.9); border-radius: 16px; border: 1px solid rgba(229,231,235,0.6);',
                ],
                'is_active' => true,
                'is_default' => true,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 1,
            ],
            [
                'type' => 'card_style',
                'option_id' => 'glass',
                'name' => 'Glassmorphism',
                'description' => 'Frosted glass effect with strong blur — premium translucent look.',
                'config' => [
                    'class' => 'bg-white/10 backdrop-blur-xl rounded-3xl border border-white/20 shadow-xl',
                    'previewCss' => 'background: linear-gradient(135deg, rgba(255,255,255,0.2) 0%, rgba(255,255,255,0.05) 100%); backdrop-filter: blur(20px); -webkit-backdrop-filter: blur(20px); border-radius: 24px; border: 1px solid rgba(255,255,255,0.2); box-shadow: 0 25px 50px -12px rgba(0,0,0,0.25);',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 2,
            ],
            [
                'type' => 'card_style',
                'option_id' => 'neumorph',
                'name' => 'Neumorphism',
                'description' => 'Soft extruded 3D surface with dual shadow — modern tactile look.',
                'config' => [
                    'class' => 'rounded-3xl shadow-[12px_12px_24px_rgba(0,0,0,0.08),-12px_-12px_24px_rgba(255,255,255,0.9)]',
                    'previewCss' => 'background: #F3F4F6; border-radius: 24px; box-shadow: 10px 10px 20px rgba(0,0,0,0.06), -10px -10px 20px rgba(255,255,255,0.95);',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 3,
            ],
            [
                'type' => 'card_style',
                'option_id' => 'frosted-bordered',
                'name' => 'Frosted Bordered',
                'description' => 'Thick white border around glassy card — framed gallery style.',
                'config' => [
                    'class' => 'bg-white/5 backdrop-blur-xl rounded-3xl border-[3px] border-white/40',
                    'previewCss' => 'background: linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0.02)); backdrop-filter: blur(16px); border-radius: 24px; border: 3px solid rgba(255,255,255,0.4);',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 4,
            ],
            [
                'type' => 'card_style',
                'option_id' => 'neon-outline',
                'name' => 'Neon Outline',
                'description' => 'Glowing border with dark inner surface — nightlife/cyber style.',
                'config' => [
                    'class' => 'bg-black/20 backdrop-blur-md rounded-3xl border border-cyan-400/50 shadow-[0_0_30px_rgba(34,211,238,0.3)]',
                    'previewCss' => 'background: rgba(0,0,0,0.2); backdrop-filter: blur(14px); border-radius: 24px; border: 1px solid rgba(34,211,238,0.6); box-shadow: 0 0 30px rgba(34,211,238,0.3);',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 5,
            ],

            // ========== BACKGROUND ANIMATIONS (screensaver-like ambient effects) ==========
            [
                'type' => 'bg_animation',
                'option_id' => 'none',
                'name' => 'None / Static',
                'description' => 'Plain static background — fastest performance.',
                'config' => [
                    'component' => null,
                    'previewCss' => 'background: transparent;',
                ],
                'is_active' => true,
                'is_default' => true,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 1,
            ],
            [
                'type' => 'bg_animation',
                'option_id' => 'particles',
                'name' => 'Floating Particles',
                'description' => 'Soft glowing dots drifting slowly — ambient screensaver feel.',
                'config' => [
                    'component' => 'BgParticles',
                    'previewCss' => 'background: radial-gradient(circle at 20% 30%, rgba(255,255,255,0.2) 0%, transparent 40%), radial-gradient(circle at 70% 60%, rgba(255,255,255,0.15) 0%, transparent 45%);',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 2,
            ],
            [
                'type' => 'bg_animation',
                'option_id' => 'aurora',
                'name' => 'Aurora Borealis',
                'description' => 'Slow moving aurora gradients — dreamy premium effect.',
                'config' => [
                    'component' => 'BgAurora',
                    'previewCss' => 'background: linear-gradient(120deg, rgba(56,189,248,0.4), rgba(168,85,247,0.4), rgba(236,72,153,0.4)); background-size: 300% 300%; animation: aurora 12s ease infinite;',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 3,
            ],
            [
                'type' => 'bg_animation',
                'option_id' => 'mesh-gradient',
                'name' => 'Gradient Mesh',
                'description' => 'Animated 3-blob color mesh — trendy modern splash.',
                'config' => [
                    'component' => 'BgMesh',
                    'previewCss' => 'background: radial-gradient(circle at 20% 20%, rgba(99,102,241,0.35) 0%, transparent 50%), radial-gradient(circle at 80% 30%, rgba(236,72,153,0.3) 0%, transparent 50%), radial-gradient(circle at 50% 80%, rgba(20,184,166,0.3) 0%, transparent 50%);',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 4,
            ],
            [
                'type' => 'bg_animation',
                'option_id' => 'starfield',
                'name' => 'Starfield',
                'description' => 'Gentle twinkling stars — perfect for dark/tech themes.',
                'config' => [
                    'component' => 'BgStars',
                    'previewCss' => 'background: radial-gradient(2px 2px at 20% 30%, rgba(255,255,255,0.9), transparent 50%), radial-gradient(1.5px 1.5px at 60% 70%, rgba(255,255,255,0.7), transparent 50%), radial-gradient(1px 1px at 40% 10%, rgba(255,255,255,0.8), transparent 50%), radial-gradient(1.5px 1.5px at 85% 45%, rgba(255,255,255,0.7), transparent 50%);',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 5,
            ],
            [
                'type' => 'bg_animation',
                'option_id' => 'slow-waves',
                'name' => 'Slow Waves',
                'description' => 'Calm horizontal sine wave lines — peaceful ambient.',
                'config' => [
                    'component' => 'BgWaves',
                    'previewCss' => 'background: repeating-linear-gradient(transparent, transparent 20px, rgba(255,255,255,0.08) 20px, rgba(255,255,255,0.08) 22px);',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 6,
            ],
            [
                'type' => 'bg_animation',
                'option_id' => 'sparkle',
                'name' => 'Magic Sparkle',
                'description' => 'Occasional sparkle bursts — premium celebratory feel.',
                'config' => [
                    'component' => 'BgSparkle',
                    'previewCss' => 'background: radial-gradient(circle at 25% 25%, rgba(255,255,255,0.25) 0%, transparent 10%), radial-gradient(circle at 75% 65%, rgba(255,255,255,0.25) 0%, transparent 10%), radial-gradient(circle at 50% 45%, rgba(255,255,255,0.15) 0%, transparent 12%);',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 7,
            ],
            [
                'type' => 'bg_animation',
                'option_id' => 'grid-dots',
                'name' => 'Dotted Grid',
                'description' => 'Soft dot matrix pattern — clean corporate texture.',
                'config' => [
                    'component' => 'BgGridDots',
                    'previewCss' => 'background-image: radial-gradient(rgba(255,255,255,0.15) 1px, transparent 1px); background-size: 24px 24px;',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 8,
            ],

            // ========== PROFILE STYLES (Layout Variant) ==========
            [
                'type' => 'profile_style',
                'option_id' => 'classic',
                'name' => 'Classic Center',
                'description' => 'Centered avatar with vertical stack — traditional business card layout.',
                'config' => [
                    'avatarPosition' => 'center',
                    'layout' => 'vertical',
                ],
                'is_active' => true,
                'is_default' => true,
                'available_plans' => ['basic', 'premium', 'business'],
                'display_order' => 1,
            ],
            [
                'type' => 'profile_style',
                'option_id' => 'side-avatar',
                'name' => 'Side Avatar',
                'description' => 'Left-aligned avatar with right content — modern compact layout.',
                'config' => [
                    'avatarPosition' => 'left',
                    'layout' => 'horizontal',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 2,
            ],
            [
                'type' => 'profile_style',
                'option_id' => 'cover-photo',
                'name' => 'Cover + Profile',
                'description' => 'Hero cover banner at top with profile below — magazine style.',
                'config' => [
                    'avatarPosition' => 'center',
                    'layout' => 'cover',
                    'requireCoverImage' => true,
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 3,
            ],

            // ========== FEATURE TOGGLES ==========
            [
                'type' => 'feature_toggle',
                'option_id' => 'layout_designer',
                'name' => 'Layout Designer',
                'description' => 'Allow users to customize the order and visibility of sections on their landing page.',
                'config' => [
                    'icon' => 'heroicons:squares-2x2',
                    'category' => 'customization',
                ],
                'is_active' => true,
                'is_default' => false,
                'available_plans' => ['premium', 'business'],
                'display_order' => 100,
            ],
        ];

        foreach ($options as $option) {
            DB::table('profile_design_options')->updateOrInsert(
                ['type' => $option['type'], 'option_id' => $option['option_id']],
                array_merge($option, [
                    'config' => json_encode($option['config']),
                    'available_plans' => json_encode($option['available_plans']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        $this->command->info('✅ Profile Design Options seeded: ' . count($options) . ' entries (themes, fonts, buttons, card styles, bg animations, layouts).');
    }
}
